private_gsheets_url = "https://docs.google.com/spreadsheets/d/1yQCZqRweD7FLCAEFZagH00WmSQ1Pb8iVWTTnC6X3jLM/edit#gid=452671349"

[gcp_service_account]
type = "service_account"
project_id = "FinanceStreamlit"
private_key_id = "FS"
private_key = "FSK"
client_email = "ju.michoux@gmail.com"
client_id = ""
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "xxx"
